{-# OPTIONS -w #-}
module Hydra.BNFC.AbsHydra where

-- Haskell module generated by the BNF converter

newtype LIdent = LIdent String deriving (Eq,Ord,Show)
newtype HsExpr = HsExpr String deriving (Eq,Ord,Show)
data SigRel =
   SigRel Pattern [Equation]
  deriving (Eq,Ord,Show)

data SigFun =
   SigFun Pattern BExpr
  deriving (Eq,Ord,Show)

data Pattern =
   PatternWild
 | PatternName PatternNameQual LIdent
 | PatternTuple [Pattern]
  deriving (Eq,Ord,Show)

data PatternNameQual =
   PatternNameQualEmpty
 | PatternNameQualFlow
  deriving (Eq,Ord,Show)

data Equation =
   EquationEqual Expr Expr
 | EquationInit Expr Expr
 | EquationReinit Expr Expr
 | EquationLocal LIdent [LIdent]
 | EquationConnect LIdent LIdent [LIdent]
 | EquationConnectFlow LIdent LIdent [LIdent]
 | EquationMonitor LIdent
 | EquationSigRelApp HsExpr Expr
  deriving (Eq,Ord,Show)

data Expr =
   ExprAdd Expr Expr
 | ExprSub Expr Expr
 | ExprDiv Expr Expr
 | ExprMul Expr Expr
 | ExprPow Expr Expr
 | ExprNeg Expr
 | ExprApp Expr Expr
 | ExprVar LIdent
 | ExprAnti HsExpr
 | ExprInt Integer
 | ExprReal Double
 | ExprTuple [Expr]
  deriving (Eq,Ord,Show)

data BExpr =
   BExprOr BExpr BExpr
 | BExprAnd BExpr BExpr
 | BExprLt Expr Expr
 | BExprLte Expr Expr
 | BExprGt Expr Expr
 | BExprGte Expr Expr
 | BExprNot BExpr
 | BExprTrue
 | BExprFalse
  deriving (Eq,Ord,Show)

